apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-fallback-104131
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-fallback-104131
  template:
    metadata:
      labels:
        app: k8s-fallback-104131
    spec:
      containers:
      - name: fallback-container
        image: nginx:latest
        ports:
        - containerPort: 80