import os
from datetime import datetime
import json

ROOT = os.environ.get("OMNICLAW_ROOT", os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))

TARGETS = [
    # (Path, Category, Type)
    (os.path.join(ROOT, "brain", "knowledge", "repos"), "LOCAL_CORE", "REPO"),
    (os.path.join(ROOT, "ecosystem", "plugins"), "LOCAL_CORE", "PLUGIN"),
    (os.path.join(ROOT, "ecosystem", "tools"), "LOCAL_CORE", "TOOL"),
    (os.path.join(ROOT, "ecosystem", "skills"), "LOCAL_CORE", "SKILL"),
    (os.path.join(ROOT, "ecosystem", "workforce", "subagents"), "LOCAL_CORE", "AGENT"),
    (os.path.join(ROOT, "system", "security", "QUARANTINE", "vetted", "repos"), "LOCAL_CORE", "REPO"),
]

REGISTRY_OUT = os.path.join(ROOT, "system", "registry", "SYSTEM_INDEX.yaml")

def generate_safe_id(name, cat, typ):
    clean = "".join(c if c.isalnum() else "_" for c in name.lower())
    return f"{cat.lower()}_{typ.lower()}_{clean}"

def build_registry():
    entities = []

    for path, cat, typ in TARGETS:
        if not os.path.exists(path):
            continue

        for item in os.listdir(path):
            ipath = os.path.join(path, item)
            if os.path.isdir(ipath):
                e_id = generate_safe_id(item, cat, typ)
                
                # Make path relative to ROOT to keep it perfectly portable
                rel_path = os.path.relpath(ipath, ROOT).replace("\\", "/")
                
                entities.append({
                    "id": e_id,
                    "name": item,
                    "path": rel_path,
                    "category": cat,
                    "type": typ
                })

    with open(REGISTRY_OUT, "w", encoding="utf-8") as f:
        f.write("# ==========================================\n")
        f.write("# 🌐 AI OS MASTER REGISTRY (SYSTEM_INDEX)\n")
        f.write("# ==========================================\n")
        f.write("# AUTO-GENERATED BY registry_indexer.py\n")
        f.write(f"# LAST SCAN: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        f.write("ai_os_system_index:\n")
        f.write(f"  total_entities: {len(entities)}\n")
        f.write("  entities:\n")

        for e in entities:
            # Escape single quotes in name and path
            name = str(e['name']).replace("'", "''")
            path = str(e['path']).replace("'", "''")
            f.write(f"    - id: '{e['id']}'\n")
            f.write(f"      name: '{name}'\n")
            f.write(f"      path: '{path}'\n")
            f.write(f"      category: '{e['category']}'\n")
            f.write(f"      type: '{e['type']}'\n")

    print(f"[DONE] Indexed {len(entities)} entities into {REGISTRY_OUT}")

if __name__ == "__main__":
    build_registry()
