import os
import re

AGENT_DIR = r"D:\OmniClaw\ecosystem\workforce\agents"
DEPT_DIR = r"D:\OmniClaw\ecosystem\workforce\departments"

# 1. OHD Healing Config
OHD_WATERMARK = "\n*Regenerated by OHD Health Daemon. Zero-Trust Policy Enforced.*"
SYS_PROMPT_TPL = f"""# SYSTEM PROMPT
You are a specialized autonomous agent operating within OmniClaw OS.
Follow all OAP Pipeline protocols and ensure receipts are dropped upon task completion.
{OHD_WATERMARK}
"""
SKILL_TPL = f"""# SKILL REGISTER
No manual skills formally allocated yet. Capabilities deferred to Department pipeline.
{OHD_WATERMARK}
"""

# 2. OA Heuristics Config
heuristics = {
    "qa_testing": ["test", "qa", "lint", "mypy", "pyright"],
    "ux_design": ["ui", "ux", "frontend", "react", "vue"],
    "rd": ["ai", "ml", "qwen", "claude", "llm", "finrl", "generative", "notebooklm"],
    "marketing": ["growth", "content", "tiktok", "social", "chart", "newspaper", "videocaptioner"],
    "legal": ["legal", "compliance", "law", "grc"],
    "hr_people": ["hr", "org", "scrum", "pmo", "cost", "manager"],
    "security_grc": ["sec", "strix", "guard", "cloudflared"],
    "it_infra": ["devops", "sre", "mac", "deploy", "infra", "termux"],
    "engineering": ["go", "git", "repo", "omniclaw", "antigravity", "tinyclaw", "code"],
    "asset_library": ["library", "docs"],
    "operations": ["monitor", "support", "bridge", "channel", "health", "intake"]
}

DEFAULT_DEPT = "engineering"

print("--- OHD: Healing Missing Core Files ---")
agents = [d for d in os.listdir(AGENT_DIR) if os.path.isdir(os.path.join(AGENT_DIR, d))]
for a in agents:
    path = os.path.join(AGENT_DIR, a)
    prompt_path = os.path.join(path, "system_prompt.md")
    skill_path = os.path.join(path, "SKILL.md")
    
    if not os.path.exists(prompt_path):
        with open(prompt_path, "w", encoding="utf-8") as f:
            f.write(SYS_PROMPT_TPL)
    
    if not os.path.exists(skill_path):
        with open(skill_path, "w", encoding="utf-8") as f:
            f.write(SKILL_TPL)

print("\n--- OA: Assimilating Stray Agents ---")
# Build a list of mapped agents to skip them
mapped_agents_normalized = set()
depts = [d for d in os.listdir(DEPT_DIR) if os.path.isdir(os.path.join(DEPT_DIR, d))]
for d in depts:
    path = os.path.join(DEPT_DIR, d, 'DEPARTMENT.md')
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            matches = re.findall(r'- \*\*(.*?)\*\*', f.read())
            for m in matches:
                mapped_agents_normalized.add(m.strip().lower().replace('-', '_'))

unmapped = [a for a in agents if a.lower().replace('-', '_') not in mapped_agents_normalized]

assigned_count = 0
for a in unmapped:
    # Match heuristic
    target_dept = DEFAULT_DEPT
    aname = a.lower()
    for dept, keywords in heuristics.items():
        if any(kw in aname for kw in keywords):
            target_dept = dept
            break

    # Re-write Agent.md to point to target_dept
    agent_md_path = os.path.join(AGENT_DIR, a, "AGENT.md")
    if os.path.exists(agent_md_path):
        with open(agent_md_path, "r", encoding="utf-8") as f:
            content = f.read()
        content = content.replace("Department: unassigned", f"Department: {target_dept}")
        # Sometimes it might just be missing the field, but our clean script earlier made sure it has 'unassigned'.
        with open(agent_md_path, "w", encoding="utf-8") as f:
            f.write(content)

    # Append to target department Roster
    dept_md_path = os.path.join(DEPT_DIR, target_dept, "DEPARTMENT.md")
    if os.path.exists(dept_md_path):
        with open(dept_md_path, "r", encoding="utf-8") as f:
            lines = f.readlines()
            
        # Find Roster section, append to end of roster
        roster_idx = -1
        for i, l in enumerate(lines):
            if "## Core Capabilities" in l or ("## " in l and roster_idx != -1):
                roster_idx = i
                break
            elif "## Workforce Roster" in l:
                roster_idx = i + 1
                
        if roster_idx != -1:
            # Insert before the next section
            insert_idx = roster_idx
            while insert_idx < len(lines) and not lines[insert_idx].startswith("## "):
                insert_idx += 1
                
            lines.insert(insert_idx, f"- **{a}** (active): *Assimilated by OA Pipeline*\n")
            with open(dept_md_path, "w", encoding="utf-8") as f:
                f.write("".join(lines))
    assigned_count += 1

print(f"Assimilated {assigned_count} orphaned agents into Departments successfully.")
