import os
import re
import json
from datetime import datetime

def _extract_functions(content: str) -> list:
    """Extract standard function signatures natively."""
    fnames = re.findall(r'def\s+([a-zA-Z0-9_]+)\(', content)
    return list(set(fnames))

def _identify_technologies(content: str) -> list:
    """Detect frameworks purely via regex scanning."""
    techs = []
    content_lower = content.lower()
    if 'fastapi' in content_lower: techs.append("FastAPI")
    if 'react' in content_lower: techs.append("React")
    if 'sqlalchemy' in content_lower: techs.append("SQLAlchemy")
    if 'express' in content_lower: techs.append("Express.js")
    if 'tensorflow' in content_lower or 'torch' in content_lower: techs.append("AI/ML")
    return list(set(techs))

def analyze_and_forge_natively(repo_path: str, repo_name: str) -> dict:
    """
    Acts as the Native Fallback Engine when LLM is offline.
    Extracts structure and constructs a fully functional AGENT.md profile
    equipped with default core-survival skills.
    """
    print(f"\033[93m[HEURISTICS]\033[0m Activating NATIVE Heuristic Engine for: {repo_name}")
    
    extracted_funcs = []
    technologies = []
    files_scanned = 0
    total_size = 0
    
    # 1. Broad Directory Traversal
    for root, dirs, files in os.walk(repo_path):
        if ".git" in root or "__pycache__" in root: continue
        for file in files:
            files_scanned += 1
            if file.endswith('.py') or file.endswith('.js') or file.endswith('.ts'):
                try:
                    fpath = os.path.join(root, file)
                    total_size += os.path.getsize(fpath)
                    with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
                        buf = f.read(50000)
                        extracted_funcs.extend(_extract_functions(buf))
                        technologies.extend(_identify_technologies(buf))
                except:
                    pass

    # Deduplicate
    technologies = list(set(technologies))
    extracted_funcs = list(set(extracted_funcs))[:30] # Cap to top 30 functions to avoid bloating
    
    # 2. Logic to Guess Asset Type
    rtype = "agent"
    if "api" in repo_name.lower() or "FastAPI" in technologies:
        rtype = "api"
    elif "plugin" in repo_name.lower():
        rtype = "plugin"
    elif "workflow" in repo_name.lower() or "chain" in repo_name.lower():
        rtype = "workflow"

    # 3. Assemble the Heuristic Profile
    ts = datetime.now().isoformat()
    tech_str = ", ".join(technologies) if technologies else "Standard Python/JS Generic"
    funcs_str = "\n".join([f"- `{func}()`: Native function hook" for func in extracted_funcs[:15]])
    if not funcs_str: funcs_str = "- No distinct structural functions identified."

    # 4. Inject Core Fallback Survival Skills so it is powerful even without LLM
    fallback_skills = """
## Core OS Injected Skills (Heuristic Survival Pack)
- `HEURISTIC_FILE_READ`: Can natively read text files bypassing LLM processing.
- `HEURISTIC_DIR_SCAN`: Can list directory structures natively.
- `SYSTEM_PING`: Can ping OBD Harbor to check network viability.
"""

    agent_md = f"""---
id: {repo_name}
type: {rtype}
owner: OA_HEURISTIC_FALLBACK
status: native_forced
created_at: {ts}
technologies: [{tech_str}]
---

# {repo_name.upper()} 

> [!WARNING]
> This capability profile was **NATIVELY FORGED** using Syntax Heuristics because the Core LLM Service was offline. 

## Architectural Summary
- **Type**: {rtype.capitalize()}
- **Scanned Density**: {files_scanned} files analyzed (Approx {total_size//1024} KB code mass).
- **Detected Frameworks**: {tech_str}

## Heuristic Capabilities (Function Signatures)
The engine has syntactically isolated the following potential execution hooks:
{funcs_str}

{fallback_skills}

---
*Generated by OA Heuristics Engine*
"""

    return {
        "AGENT.md": agent_md,
        "type": rtype
    }
