import os
import json
import logging
import sys
from pathlib import Path

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

ROOT_DIR = Path(os.getenv("OMNICLAW_ROOT", Path(__file__).resolve().parents[2]))
SKILLS_DIR = ROOT_DIR / "ecosystem" / "skills"
REGISTRY_FILE = SKILLS_DIR / "SKILL_REGISTRY.json"

WATERMARK_TEXT = """# {skill_name}

> 🛡️ OmniClaw V5.0 Authenticated Skill Profile | Auto-Assimilated

## Competency Profile
This directory houses the raw skill payload for the **{skill_name}** identity. 
It has been safely isolated in the Passive Storage structure.

### Execution Boundaries
- **System Tier:** 2 (Sandbox)
- **Status:** Active
- **Direct Execution:** Forbidden (Requires Harbor/Orchestrator context load)

---
*Generated by OmniClaw Assimilation Pipeline*
"""

def generate_schema_json(folder_name):
    # Converts snake_case to Title Case roughly
    human_name = folder_name.replace("_", " ").title()
    return {
        "id": folder_name,
        "name": human_name,
        "version": "1.0.0",
        "tier": 2,
        "status": "active",
        "path": f"$OMNICLAW_ROOT/ecosystem/skills/{folder_name}/SKILL.md",
        "accessible_by": ["Orchestrator", "Claude Code"],
        "dependencies": [],
        "exposed_functions": [],
        "consumed_by": [],
        "emits_events": [],
        "listens_to": [],
        "tags": ["auto-assimilated"]
    }


def canonicalize_skill_id(raw_id):
    if raw_id is None:
        return None

    canonical_id = str(raw_id).strip()
    for suffix in ("_agent_skill", "_skill"):
        if canonical_id.endswith(suffix):
            canonical_id = canonical_id[: -len(suffix)]
            break

    return canonical_id or None


def normalize_schema_data(schema_data, skill_id, skill_md_path):
    normalized = dict(schema_data)

    raw_id = normalized.get("id")
    normalized_id = canonicalize_skill_id(raw_id) or skill_id
    normalized["id"] = normalized_id

    if "path" not in normalized or not normalized.get("path"):
        normalized["path"] = f"$OMNICLAW_ROOT/ecosystem/skills/{skill_id}/SKILL.md"

    if "name" not in normalized or not normalized.get("name"):
        normalized["name"] = skill_id.replace("_", " ").title()

    return normalized


def repair_skill_metadata(skill_id, skill_dir, schema_path, skill_md_path, readme_path):
    human_name = skill_id.replace("_", " ").title()
    repaired = []

    if not skill_md_path.exists():
        with open(skill_md_path, "w", encoding="utf-8") as f:
            f.write(f"---\nid: {skill_id}\nname: {human_name}\ntier: 2\nstatus: active\n---\n\n# {human_name}\n[Skill logic here]\n")
        repaired.append("SKILL.md")

    if not schema_path.exists():
        schema_data = generate_schema_json(skill_id)
        with open(schema_path, "w", encoding="utf-8") as f:
            json.dump(schema_data, f, indent=4)
        repaired.append("schema.json")

    if not readme_path.exists():
        readme_content = WATERMARK_TEXT.format(skill_name=human_name)
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(readme_content)
        repaired.append("README.md")

    return repaired

def process_skills(repair_mode=False):
    registry = {}
    total_processed = 0
    invalid_skills = []

    if not SKILLS_DIR.exists():
        logging.error(f"Skills directory not found: {SKILLS_DIR}")
        return 1

    for item in SKILLS_DIR.iterdir():
        if item.is_dir() and not item.name.startswith("_"):
            skill_id = item.name
            schema_path = item / "schema.json"
            readme_path = item / "README.md"
            skill_md_path = item / "SKILL.md"

            repaired_files = []
            if repair_mode:
                repaired_files = repair_skill_metadata(skill_id, item, schema_path, skill_md_path, readme_path)
                if repaired_files:
                    logging.warning(
                        "Repair mode generated metadata for '%s': %s",
                        skill_id,
                        ", ".join(repaired_files),
                    )

            issues = []
            if not skill_md_path.exists():
                issues.append("missing SKILL.md")

            schema_data = None
            if not schema_path.exists():
                issues.append("missing schema.json")
            else:
                try:
                    with open(schema_path, "r", encoding="utf-8") as f:
                        schema_data = json.load(f)
                    schema_data = normalize_schema_data(schema_data, skill_id, skill_md_path)
                except Exception as e:
                    issues.append(f"invalid schema.json: {e}")

            if schema_data:
                if schema_data.get("id") != skill_id:
                    issues.append(f"schema id mismatch: expected '{skill_id}', got '{schema_data.get('id')}'")
                if "path" not in schema_data or not schema_data.get("path"):
                    issues.append("schema.json missing 'path'")

            if issues:
                invalid_skills.append((skill_id, issues))
                logging.error("Skipping skill '%s': %s", skill_id, "; ".join(issues))
                continue

            if schema_data:
                registry[skill_id] = schema_data

            total_processed += 1

    with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
        json.dump(registry, f, indent=4)

    logging.info(f"Assimilation complete. Registered {total_processed} valid skills.")
    if invalid_skills:
        logging.error("Found %s invalid skills. Registry written with valid entries only.", len(invalid_skills))
        return 1
    logging.info(f"Registry compiled successfully into {REGISTRY_FILE.name} with {len(registry)} skills.")
    return 0

if __name__ == "__main__":
    repair_mode = "--repair" in sys.argv or os.getenv("OMNICLAW_ASSIMILATOR_REPAIR") == "1"
    raise SystemExit(process_skills(repair_mode=repair_mode))
