import os
import json
import logging
from pathlib import Path

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

ROOT_DIR = Path(r"D:\OmniClaw")
SKILLS_DIR = ROOT_DIR / "ecosystem" / "skills"
REGISTRY_FILE = SKILLS_DIR / "SKILL_REGISTRY.json"

WATERMARK_TEXT = """# {skill_name}

> 🛡️ OmniClaw V5.0 Authenticated Skill Profile | Auto-Assimilated

## Competency Profile
This directory houses the raw skill payload for the **{skill_name}** identity. 
It has been safely isolated in the Passive Storage structure.

### Execution Boundaries
- **System Tier:** 2 (Sandbox)
- **Status:** Active
- **Direct Execution:** Forbidden (Requires Harbor/Orchestrator context load)

---
*Generated by OmniClaw Assimilation Pipeline*
"""

def generate_schema_json(folder_name):
    # Converts snake_case to Title Case roughly
    human_name = folder_name.replace("_", " ").title()
    return {
        "id": folder_name,
        "name": human_name,
        "version": "1.0.0",
        "tier": 2,
        "status": "active",
        "path": f"$OMNICLAW_ROOT\\ecosystem\\skills\\{folder_name}\\SKILL.md",
        "accessible_by": ["Orchestrator", "Claude Code"],
        "dependencies": [],
        "exposed_functions": [],
        "consumed_by": [],
        "emits_events": [],
        "listens_to": [],
        "tags": ["auto-assimilated"]
    }

def process_skills():
    registry = {}
    total_processed = 0
    missing_skill_md_count = 0

    if not SKILLS_DIR.exists():
        logging.error(f"Skills directory not found: {SKILLS_DIR}")
        return

    for item in SKILLS_DIR.iterdir():
        if item.is_dir() and not item.name.startswith("_"):
            skill_id = item.name
            human_name = skill_id.replace("_", " ").title()
            
            schema_path = item / "schema.json"
            readme_path = item / "README.md"
            skill_md_path = item / "SKILL.md"

            # 1. Flag missing SKILL.md
            if not skill_md_path.exists():
                missing_skill_md_count += 1
                # Auto-generate a dummy SKILL.md so it doesn't break
                with open(skill_md_path, "w", encoding="utf-8") as f:
                    f.write(f"---\nid: {skill_id}\nname: {human_name}\ntier: 2\nstatus: active\n---\n\n# {human_name}\n[Skill logic here]\n")

            # 2. Write schema.json if missing
            schema_data = None
            if not schema_path.exists():
                schema_data = generate_schema_json(skill_id)
                with open(schema_path, "w", encoding="utf-8") as f:
                    json.dump(schema_data, f, indent=4)
            else:
                try:
                    with open(schema_path, "r", encoding="utf-8") as f:
                        schema_data = json.load(f)
                except Exception as e:
                    # Overwrite broken schema
                    schema_data = generate_schema_json(skill_id)
                    with open(schema_path, "w", encoding="utf-8") as f:
                        json.dump(schema_data, f, indent=4)
            
            # 3. Add to master registry
            if schema_data:
                registry[skill_id] = schema_data

            # 4. Write README.md with Watermark if missing
            if not readme_path.exists():
                readme_content = WATERMARK_TEXT.format(skill_name=human_name)
                with open(readme_path, "w", encoding="utf-8") as f:
                    f.write(readme_content)

            total_processed += 1

    # Write Master Registry
    with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
        json.dump(registry, f, indent=4)

    logging.info(f"Assimilation Complete. {total_processed} formatting operations finalized.")
    logging.info(f"Fixed {missing_skill_md_count} empty SKILL.md endpoints.")
    logging.info(f"Registry compiled successfully into {REGISTRY_FILE.name} with {len(registry)} skills.")

if __name__ == "__main__":
    process_skills()
